<?php

namespace ContainerGnKznnd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LjCpe4eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LjCpe4e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LjCpe4e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'listeRepository' => ['privates', 'App\\Repository\\ListeRepository', 'getListeRepositoryService', true],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
            'session' => ['privates', '.errored..service_locator.LjCpe4e.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.LjCpe4e": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
        ], [
            'listeRepository' => 'App\\Repository\\ListeRepository',
            'registry' => '?',
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
        ]);
    }
}
