<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBKQTHSE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBKQTHSE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBKQTHSE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBKQTHSE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBKQTHSE\App_KernelDevDebugContainer([
    'container.build_hash' => 'BKQTHSE',
    'container.build_id' => '2c7e80fb',
    'container.build_time' => 1652882680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBKQTHSE');
